-- Migration user: data manipulation + schema changes (CREATE/ALTER/DROP...).
-- Used only by the migration CLI.
CREATE USER IF NOT EXISTS '${JOBRADAR_MIGRATOR_USER}'@'%' IDENTIFIED BY '${JOBRADAR_MIGRATOR_PASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES
    ON `${MYSQL_DATABASE}`.*
    TO '${JOBRADAR_MIGRATOR_USER}'@'%';
FLUSH PRIVILEGES;
