[package]
name = "web"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Matt4401/JobRadar"

[dependencies]
db = { path = "../db" }
shared = { path = "../shared" }
scraper = { path = "../scraper" }
tokio = { version = "1", features = ["full"] }
axum = "0.8.9"
serde = { version = "1.0", features = ["derive"] }
askama = "0.16.0"
